FROM golang:1.6-alpine

MAINTAINER minimum@cepave.com

ARG ENTRYFILE=openfalcon-build.sh
ARG BRANCH
ENV BRANCH=${BRANCH:-develop} REPO=github.com/Cepave/open-falcon-backend
ENV WORKPATH=${GOPATH}/src/${REPO}
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:$GOPATH/bin

# Build Open-Falcon Components
VOLUME /package

RUN \
  apk add --update git g++ bash perl make \
  && mkdir -p ${WORKPATH}

COPY ${ENTRYFILE} build.sh

# Start
ENTRYPOINT ["/bin/bash"]
CMD ["build.sh"]
